### ISSUE TITLE
Handle PKCS12 files

### ISSUE THREAD

**Issue by roguh** [rustls/pemfile#17]
Hi, how could I load a PKCS12 file ~with a password~ for use in `rustls`? Edit: I see this library doesn't support PKCS8 with passwords.

I see there used to be a `rustls::internal::pemfile::pkcs12_import` function, and there's a function for loading a pkcs8 file.

I'm resorting to loading the PKCS12 with the `openssl` crate, then re-encoding that to a PEM `&[u8]` that I pass to `rustls`. Is there another way?

**Comment by roguh** [comment]
I'll look into using this crate or another pure Rust PKCS12 parser: https://github.com/jack-fortanix/pkcs12

For future reference, here's how I parsed a PKCS12 with the heavy openssl crate:

```
    let openssl_pkcs12 = openssl::pkcs12::Pkcs12::from_der(server_identity_pkcs12_der.as_slice())
        .expect("Failed to parse identity file")
        .parse2(password)
        .expect("Failed to parse identity file with given password");
    let cert = openssl_pkcs12
        .cert
        .expect("No TLS certificate found in identity file");
    let ca_cert_chain: Vec<_> = openssl_pkcs12
        .ca
        .map(|stack| stack.into_iter().collect())
        .expect("At least 1 CA cert is needed");

    // TODO check validity of cert, etc
    let private_key = openssl_pkcs12
        .pkey
        .expect("No TLS private key found in identity file");

    println!(
        "Loaded cert with Subject alt names (SNA): {:?}",
        &cert.subject_alt_names().expect("Cert must have SNA field.")
    );

    // Rustls has no support for pkcs12
    let mut cert_chain = ca_cert_chain.clone();
    cert_chain.insert(0, cert);
    let an_entire_pem: Vec<_> = cert_chain
        .into_iter()
        .map(|c| c.to_pem().unwrap())
        .collect();

    let der_encoded_cert_chain: Vec<tokio_rustls::rustls::Certificate> =
        rustls_pemfile::certs(&mut an_entire_pem.concat().as_ref())
            .expect("Parse DER")
            .into_iter()
            .map(|c| tokio_rustls::rustls::Certificate(c))
            .collect();

    let der_encoded_pkey = tokio_rustls::rustls::PrivateKey(
        private_key
            .private_key_to_der()
            .expect("Unable to encode private key as DER"),
    );

    let config = ServerConfig::builder()
        .with_safe_default_cipher_suites()
        .with_safe_default_kx_groups()
        .with_protocol_versions(&[&tokio_rustls::rustls::version::TLS13])
        .expect("Unable to set TLS settings")
        .with_no_client_auth()
        .with_single_cert(der_encoded_cert_chain, der_encoded_pkey)
        .expect("Unable to build rustls ServerConfig");
    let tls_acceptor = TlsAcceptor::from(std::sync::Arc::new(config));

```

Cargo.toml:
```
openssl-sys = "0.9"
openssl = "0.10"
tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.2"
```

You see this gives a fully parsed certificate that can be validated and you can analyze its metadata, I use this to print the cert's SNAs.

**Comment by djc** [comment]
See #15.

**Comment by roguh** [comment]
Thank you.

Also related: https://github.com/rusticata/x509-parser/issues/78

**Comment by svanharmelen** [comment]
Hi @roguh 👋🏻 I'm currently trying to achieve the exact same thing 😏 Did you already manage to find a solution that doesn't require the `openssl` crate?

**Comment by djc** [comment]
#15 (referenced above) mentions the p12 crate, which is advertised as "pure Rust".

**Comment by cpu** [comment]
I think we should consider this out-of-scope for `pemfile` since the `p12` crate exists and can meet the need.

**Comment by roguh** [comment]
Makes sense. Either p12 or openssl can be used for parsing these files. Calling external tool could also work, such as the openssl CLI or something more lightweight.

**Comment by gvaradarajan** [comment]
I appreciate the ideal of relying on existing tools in the Rust ecosystem, but there are situations where openssl is not an option (like in embedded contexts) and the p12 crate lacks documentation and doesn't seem to be under active development (which always causes me to hesitate when including a dependency). Could we consider reopening this issue? Is there a particular reason PEM to/from PKCS12 would not be reasonable functionality for rustls/pemfile?

**Comment by djc** [comment]
@gvaradarajan why are P12 files important to you? Where are they coming from? Can't you convert them offline?

**Comment by gvaradarajan** [comment]
@djc We're working on a microcontroller and would like to cache TLS certificates that come through via API. The chain of certificates comes in as a PEM encoded string, and caching it ends up exceeding the limits of our memory restrictions. We were hoping to save space by undoing the base64 encoding involved in PEM, but the amount of certificates in the chain can be variable so PKCS12 looked like the best storage format for our use case.

**Comment by djc** [comment]
Why couldn't you just store the DER from decoded PEM? Like, a `CertificateDer<'static>`?

(BTW this crate is pretty much deprecated, we recommend using the underlying rustls-pki-types PEM API directly.)

**Comment by gvaradarajan** [comment]
fair enough, I'll just use `Vec<CertificateDer>` from rustls-pki-types for now
