### ISSUE TITLE
Provide a function to extract private keys in any format

### ISSUE THREAD

**Issue by Will-Low** [rustls/pemfile#18]
I had a use case the other day where I needed to parse some private keys of various formats. I had to write a bit of match logic to extract the bytes for the appropriate key type, even though I didn't care about which key type it was. I think this would be a relatively common use-case.

What would you folks think about providing a function to parse all private keys in any format, returning a `Result<Vec<Vec<u8>>, Error>`?

**Comment by djc** [comment]
We already have `read_one()` and `read_all()` today, which yield an `Option<Item>` and `Vec<Item>`, respectively. How about we add an `fn key(self) -> Option<Vec<u8>>` on `Item`?

**Comment by cpu** [comment]
We puzzled through this in https://github.com/rustls/pemfile/pull/19 and came to the conclusion that the change would require adding `Clone` to `Item` to be ergonomic, but that's not appropriate for items holding private key bytes. The alternatives were about as cumbersome as the status quo and so we're going to keep things as-is for now.
