### ISSUE TITLE
Document breaking changes with 

### ISSUE THREAD

**Issue by nyurik** [rustls/pemfile#35]
Per https://github.com/rustls/pemfile/commit/6f0724bfd5db1a97341218bb22ac32fbfece4a82

These breaking changes were done, but not listed in the release notes.  Please add the following text to the release page:

```
Renamed `Item::{RSAKey, PKCS8Key, ECKey}` to `Item::{Pkcs1Key, Pkcs8Key, Sec1Key}`
```

**Comment by djc** [comment]
Done.
