### ISSUE TITLE
Certificates with indentation fail to parse

### ISSUE THREAD

**Issue by killjoy1221** [rustls/pemfile#40]
Example cert:
```
-----BEGIN CERTIFICATE-----
 MIIDaTCCAlGgAwIBAgIJAOq/zL+84IswMA0GCSqGSIb3DQEBCwUAMFoxCzAJBgNV
 BAYTAlVTMQswCQYDVQQIDAJOQzEMMAoGA1UEBwwDUlRQMQ8wDQYDVQQKDAZOZXRB
 cHAxDTALBgNVBAsMBEVTSVMxEDAOBgNVBAMMB1NTRk1DQ0EwHhcNMTcxMTAxMjEw
 OTQyWhcNMjcxMDMwMjEwOTQyWjBaMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTkMx
 DDAKBgNVBAcMA1JUUDEPMA0GA1UECgwGTmV0QXBwMQ0wCwYDVQQLDARFU0lTMRAw
 DgYDVQQDDAdTU0ZNQ0NBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
 iaD9Ee0Yrdka0I+9GTJBIW/Fp5JU6kyjaxfOldW/R9lEubegXQFhDD2Xi1HZ+fTM
 f224glB9xLJXAHhipRK01C2MgC4kSH75WL1iAiYeOBloExqmK6OCX+sdyO7RXm/H
 Ra9tN2INWdvyO2pnmxsSnq56mCMsUZLtrRKp89FWgcxLg5r8QxH7xwfh5k54rxjE
 144TD9yrIiQOgRSIRHUrVJ9l/F/gnwzP8wcNABeXwN71Mzl7mliPA703kONQIAyU
 0E0tLpmy/U8dZdMmTBZGB7jI9f95Hl1RunfwhR371a6z38kgkvwrLzl4qflfsPjw
 K9n4omNk9rCH9H9tWkxxjwIDAQABozIwMDAdBgNVHQ4EFgQU/bFyCCnqdDFKlQBJ
 ExtV6wcMYkEwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAOQMs
 Pz2iBD1+3RcSOsahB36WAwPCjgPiXXXpU+Zri11+m6I0Lq+OWtf+YgaQ8ylLmCQd
 0p1wHlYA4qo896SycrhTQfy9GlS/aQqN192k3oBGoJcMIUnGUBGuEvyZ2aDUfkzy
 JUqBe+0KaT7pkvvbRL7VUz34I7ouq9fQIRZ26vUDLTY3KM1n/DXBj3e30GHGMV3K
 NN2twuLXPNjnryfgpliHU1rwV7r1WvrCVn4StjimP2bO5HGqD/SbiYUL2M9LOuLK
 6mqY4OHumYXq3k7CHrvt0FepsN0L14LYEt1LvpPDFWP3SdN4z4KqT9AGqBaJnhhl
 Qiq8GWnAChspdBLxCg==
-----END CERTIFICATE-----
```

OpenSSL can load it via `openssl x509 -in cert.crt -noout -text`, so it is valid. Trying to parse this with rustls-pemfile (via rustls-native-certs) creates an error similar to this.

```
{ kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\": Invalid byte 32, offset 0." }
```

**Comment by ctz** [comment]
> I believe [RFC 7468](https://www.rfc-editor.org/rfc/rfc7468) is the authoritative source for the PEM encoding of a certificate

Agree. But it also says:

> Furthermore, parsers SHOULD ignore whitespace and other non-
> base64 characters and MUST handle different newline conventions.

So I think it's reasonable to expect we should parse this correctly.

**Comment by cpu** [comment]
>> Furthermore, parsers SHOULD ignore whitespace and other non-base64 characters and MUST handle different newline conventions.
> 
> So I think it's reasonable to expect we should parse this correctly.

I saw this as well, but it's a SHOULD for parsers compared to a MUST for encoders, and given the other language about ambiguities I wasn't fully convinced this crate should change. (but I don't feel very strongly)

**Comment by zanieb** [comment]
It seems pretty reasonable to warn but strip the whitespace — hopefully that's enough to encourage a report to the encoder without blocking users.

**Comment by djc** [comment]
> I saw this as well, but it's a SHOULD for parsers compared to a MUST for encoders, and given the other language about ambiguities I wasn't fully convinced this crate should change. (but I don't feel very strongly)

Given that this crate implements a parser, I think we should align with the SHOULD. I support the argument that the encoder is in the wrong here, but given the SHOULD for parsers it seems unlikely that the security considerations apply to this particular form of deviation.

**Comment by cpu** [comment]
Here's one option to consider: https://github.com/rustls/pemfile/pull/41 I used killjoy1221's `.pem` input for the integration test.
