### ISSUE TITLE
Could you add some examples?

### ISSUE THREAD

**Issue by Tahinli** [rustls/pemfile#48]
Hi, normally I use tokio-tungstenite for ws stream, but  I need wss stream. I have fullchain and privatekey pem files where I got from let's encrypt. Here is my normal code:

```rust
let socket = TcpListener::bind("192.168.1.2:2424").await.unwrap();
    let streamer_socket = TcpListener::bind("192.168.1.2:2525").await.unwrap();
        match streamer_socket.accept().await {
            Ok((streamer_tcp, streamer_info)) => {
                match tokio_tungstenite::accept_async(streamer_tcp).await {
                    Ok(ws_stream) => {
                        tokio::spawn(streamer_stream(ws_stream));
                    },
                    Err(err_val) => eprintln!("Error: TCP to WS Transform | {}", err_val),
                }
```

could this crate help me to convert this stream to wss with pem files ? If yes how ?

**Comment by djc** [comment]
I haven't really worked with tokio-tungstenite, but it looks like it builds on tokio's `AsyncRead` and `AsyncWrite` traits. You can build a TLS-enabled stream using code from the tokio-rustls crate, which has some [example code](https://github.com/rustls/tokio-rustls/blob/main/examples/server.rs). That example also uses rustls-pemfile.

**Comment by Tahinli** [comment]
> I haven't really worked with tokio-tungstenite, but it looks like it builds on tokio's `AsyncRead` and `AsyncWrite` traits. You can build a TLS-enabled stream using code from the tokio-rustls crate, which has some [example code](https://github.com/rustls/tokio-rustls/blob/main/examples/server.rs). That example also uses rustls-pemfile.

I think I did it thanks to your answer, but I couldn't figure it out solving this.
![image](https://github.com/rustls/pemfile/assets/96421894/20fa7077-fdbc-4d09-8f30-d875ef20d1db)

I gave the fullchain file and privkey in server like this:

```rust
let fullchain: io::Result<Vec<CertificateDer<'static>>> = certs(&mut BufReader::new(
        File::open("certificates/fullchain.pem").unwrap(),
    ))
    .collect();
    let fullchain = fullchain.unwrap();
    let privkey: io::Result<PrivateKeyDer<'static>> = pkcs8_private_keys(&mut BufReader::new(
        File::open("certificates/privkey.pem").unwrap(),
    ))
    .next()
    .unwrap()
    .map(Into::into);
    let privkey = privkey.unwrap();

    let config = tokio_rustls::rustls::ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(fullchain, privkey)
        .unwrap();
    let acceptor = TlsAcceptor::from(Arc::new(config));
    loop {
        match streamer_socket.accept().await {
            Ok((streamer_tcp, streamer_info)) => {
                let streamer_tcp_tls = acceptor.accept(streamer_tcp).await.unwrap();
                match tokio_tungstenite::accept_async(streamer_tcp_tls).await {
                    Ok(ws_stream) => {
                        println!(
                            "New Streamer: {:#?} | {:#?}",
                            streamer_info,
                            timer.elapsed()
                        );
                        let new_streamer = Streamer {
                            ip: streamer_info.ip(),
                            port: streamer_info.port(),
                        };
                        tokio::spawn(streamer_stream(
                            new_streamer,
                            record_producer,
                            ws_stream,
                            timer,
                        ));
                        break;
                    }
                    Err(err_val) => eprintln!("Error: TCP to WS Transform | {}", err_val),
                }
            }
            Err(err_val) => eprintln!("Error: TCP Accept Connection | {}", err_val),
        }
    }
```

If I give only cert in client side like this:
```rust
let connect_addr = "wss://192.168.1.2:2525";

    let fullchain: io::Result<Vec<CertificateDer<'static>>> = rustls_pemfile::certs(
        &mut BufReader::new(File::open("certificates/cert.pem").unwrap()),
    )
    .collect();
    let fullchain = fullchain.unwrap().pop().unwrap();
    let mut root_cert_store = RootCertStore::empty();
    root_cert_store.add(fullchain).unwrap();

    let config = ClientConfig::builder()
        .with_root_certificates(root_cert_store)
        .with_no_client_auth();

    let connector = Connector::Rustls(Arc::new(config));

    let ws_stream;
    match tokio_tungstenite::connect_async_tls_with_config(
        connect_addr,
        None,
        false,
        Some(connector),
    )
    .await
    {
        Ok(ws_stream_connected) => ws_stream = ws_stream_connected.0,
        Err(_) => {
            return;
        }
    }
```

I got unknown CA.

If I give fullchain in client it says bad certificate
![image](https://github.com/rustls/pemfile/assets/96421894/b6f0aed6-e532-462b-a849-e3b2e951c9bf)


I think giving only cert is more precise way but still don't know what is the problem and how to solve.

**Comment by djc** [comment]
The PEM files are really intended for the server -- for the client you should use one of the existing options of rustls-platform-verifier (preferably), rustls-native-certs or webpki-roots.

But this latest comment doesn't have anything to do with rustls-pemfile, I suggest you pick it up on the users forum.

**Comment by Tahinli** [comment]
> The PEM files are really intended for the server -- for the client you should use one of the existing options of rustls-platform-verifier (preferably), rustls-native-certs or webpki-roots.
> 
> But this latest comment doesn't have anything to do with rustls-pemfile, I suggest you pick it up on the users forum.

you already helped me a lot, thank you so much. I'm going to check platform verifier. I'm closing the issue.

**Comment by djc** [comment]
(We might still consider adding a few examples, I guess? Or point to tokio-rustls examples in the README, or something.)
