### ISSUE TITLE
Certificates in PEM files that starts "BEGIN TRUSTED CERTIFICATE" are ignored

### ISSUE THREAD

**Issue by szymek156** [rustls/pemfile#52]
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Describe the bug**
Hello,
I am trying to load a certificate from a PEM file that follows Openssl rules:
https://docs.openssl.org/master/man1/openssl-format-options/#format-option-arguments

In particular my `cert.pem` looks like so:
```
-----BEGIN TRUSTED CERTIFICATE-----
* valid x509 certificate *
-----END TRUSTED CERTIFICATE-----
```
(Note `TRUSTED` word).
Rustls does not parse the line `-----BEGIN TRUSTED CERTIFICATE-----` ignores the cert and reults in `NoCertificatesPresented` error.

**To Reproduce**
```
cd rustls/examples
cargo run --bin simpleserver /tmp/cert.pem /tmp/key.pem
```
In `rustls/src/server/builder.rs` I added a print to see the `CertifiedKey` struct content:
```rust
pub fn with_single_cert(...)
    ...
    let certified_key = CertifiedKey::new(cert_chain, private_key);
    println!("DEBUG: cert key {certified_key:?}");
```
Gets following result:
```
DEBUG: cert key CertifiedKey { cert: [], key: EcdsaSigningKey { algorithm: ECDSA }, ocsp: None }
```

**Applicable Version(s)**
main

**Expected behavior**
rustls should accept and correctly parse certificates generated by OpenSSL

**Additional context**
Removing the `TRUSTED` infix solves the problem, handshake is possible.
To remove the `TRUSTED`:
`openssl x509 -in cert.pem -clrtrust -out normal.pem `

Attaching example cert and key
[cert.txt](https://github.com/user-attachments/files/16564293/cert.txt)
[key.txt](https://github.com/user-attachments/files/16564301/key.txt)

Let me know what you guys think about it?

**Comment by cpu** [comment]
> transferred this issue from rustls/rustls [now](https://github.com/rustls/pemfile/issues/52#event-13823377656)

I think this would be a `rustls/pemfile` discussion.

>  It has a non-standard extension which contains PEM encodings of further certificates? Huh?

I've seen something like that before in a proprietary root from the SGX ecosystem. It's bonkers but I think that ecosystem is full of bad ideas :grimacing:

**Comment by szymek156** [comment]
Indeed this is a certificate used in remote attestation of the SGX enclave.
Certificate is generated with embedded quote (measurement) from the enclave (the non-standard extension).
The web service that runs in the enclave uses privkey and cert during TLS handshake.
Clients verify the quote from the cert, and if valid, they are assured connection is established with legit TEE.
The internal certificates comes from Intel, they contain a signature over the generated quote.

**Comment by cpu** [comment]
> "BEGIN TRUSTED CERTIFICATE" is an OpenSSL-proprietary format, I don't think we want or need to support that.

I think this is my opinion as well. Let's close this for now pending any new input.
