### ISSUE TITLE
Provide function to load a PEM *file*?

### ISSUE THREAD

**Issue by nc7s** [rustls/pemfile#9]
With a name of "pemfile" it's expected to to able to read a PEM *file*, no?

**Comment by djc** [comment]
Why don't you think it does?

**Comment by bnoctis** [comment]
Sure it can read a `File` wrapped in `BufReader`, but that's extra boilerplate. It would be nice to just `rustls_pemfile::read_file("/path/to/some.pem")`.

I can do the implementation, if you agree on that.

**Comment by djc** [comment]
Yes, that would make sense to me. Please have a look around the ecosystem to see what would make the best name for this function.

**Comment by cpu** [comment]
@bnoctis Is this still something you're interested in opening a PR for?

**Comment by bnoctis** [comment]
Sorry for the late reply; no, I was writing something and wanted it to optionally terminate TLS, but later realized that can and better be handled by something more capable. There's no immediate need now.
